# Travis-CI configuration for Bioconductor packages
# https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

matrix:
  include:
    - os: linux
      r: bioc-release
    - os: linux
      r: bioc-devel
    - os: osx
      r: bioc-release
  allow_failures:
    - os: osx
    - r: bioc-devel

branches:
  only:
    - master

env:
  global:
    - LINTR_COMMENT_BOT=true

github_packages:
  - steinbaugh/lintr

after_success:
  - Rscript -e 'lintr::lint_package()'

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: change
