language: general

services:
  - docker

branches:
  only:
    - master

before_script:
  - chmod +x *.sh

jobs:
  include:
    - stage: test
      name: "Docker"
      script: ./travis-docker.sh

after_failure:
  - ./travis-failure.sh

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: change
